---
- name: Fluentd | Ensure main config file
  template:
    src: fluentd.conf
    dest: "{{ fluentd_conf_path }}"
  notify:
    - Check Fluentd Docker Configuration

- name: Fluentd | Ensure Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ fluentd_deploy_dir }}/docker-compose.yml"
  notify:
    - Check Fluentd Docker Configuration
